### PR TITLE
Batch security updates

### PR DESCRIPTION
**Pull request by mjasikowski**
This PR:
- removes unused dependencies (like `react-router-dom`, etc)
- upgrades other deps to resolve Snyk vulnerabilities (so we can close all pending pull requests)
- converts SCSS files to be compatible with the newest version of SASS
- bumps the version to 1.3.69

Tested with latest Chrome and Firefox.

### CODE REVIEW

**Review by tgolen — APPROVED** [review]
Sounds like this one should probably be deployed since it is for security updates. Yeah?

**Comment by mjasikowski** [comment]
yup, we should deploy it

**Comment by tgolen** [comment]
OK, I'll do that this morning.

**Comment by tgolen** [comment]
Deployed!

**Pull request merged**
