### PR TITLE
Remove demolition related code from K2

### PR DESCRIPTION
**Pull request by pecanoro**
When we merged teams, we decided to get rid of the Demolition team and now that WAQ is over, I finally had some time to deal with the leftover code.

Part of https://github.com/Expensify/Expensify/issues/256949

### CODE REVIEW

**Review by tgolen — CHANGES_REQUESTED** [review]
You also need to bump versions and do the changelog thingy :D

**Comment by pecanoro** [comment]
Updated!

**Review by tgolen — APPROVED** [review]

**Comment by tgolen** [comment]
You _maybe_ don't need to deploy this. It can probably just sit and wait until there is another change that someone deploys. Unless you want to deploy it.

**Comment by pecanoro** [comment]
Yeah, I think it can wait, I think no one uses the label anymore since I removed it from the SO as well (unless someone didn't get the memo).

**Pull request merged**
