### PR TITLE
Node v20 upgrade

### PR DESCRIPTION
**Pull request by arosiclair**
$ https://github.com/Expensify/Expensify/issues/316192

- Upgrades node to v20.9.0 and npm to 10.1.0
- Fixes new lint errors

Testing this as my current version of K2

### CODE REVIEW

**Comment by arosiclair** [comment]
I asked about the license check failing [here](https://expensify.slack.com/archives/C03TQ48KC/p1699638965868269). This is ready for review in the meantime

**Comment by arosiclair** [comment]
Asked about the Snyk license failure [here](https://expensify.slack.com/archives/C03TQ48KC/p1699638965868269). This is ready for review in the meantime @srikarparsi

**Comment by arosiclair** [comment]
Marked the license check as successful in Snyk since this is an internal app

**Review by srikarparsi — APPROVED** [review]
lgtm!

**Pull request merged**
