### PR TITLE
Bump node and onyx versions

### PR DESCRIPTION
**Pull request by rafecolton**
Built locally and loaded the k2 page and an issue - looks like everything works. Not 100% sure what the implications are of updating onyx and if it can break anything, so please review. Didn't bump version numbers since there are no functional updates.

Part of https://github.com/Expensify/Expensify/issues/402520 (doesn't need to be held since it isn't dependent on the build server)

### CODE REVIEW

**Review by tgolen — DISMISSED** [review]
Yeah, that's a big Onyx bump, but I don't think anything really functional would have changed. It's almost all bug-fixes, new features, and TypeScript migrations. I installed this version locally and I'll keep running to help spot any issues that arise.

**Comment by tgolen** [comment]
Bummer, looks like the lint GH action doesn't like the version bump for some reason. Maybe they just need updated?

**Comment by rafecolton** [comment]
Oh oops, I had to fix this in another repo too, commit incoming

**Comment by rafecolton** [comment]
Hm, now the GH actions aren't running 🤔

**Comment by rafecolton** [comment]
Looks like it's stuck in queued here: https://github.com/Expensify/k2-extension/actions/runs/9421029052

**Comment by rafecolton** [comment]
Trying to force push the same commit to get GH actions to trigger

**Comment by rafecolton** [comment]
Ready to go!

**Review by tgolen — APPROVED** [review]
Nice

**Pull request merged**
