### PR TITLE
Fixed manifest for Firefox, added linting and CI

### PR DESCRIPTION
**Pull request by mjasikowski**
Fixed problems with the FF extension by using the `web-ext` package from Mozilla, which helps with linting. 
Web-ext linting was also added as a step to GitHub actions, so we can be sure it's compatible with Firefox without having to first package and upload to addons.mozilla.org.

### CODE REVIEW

**Comment by mjasikowski** [comment]
Not sure while snyk licensing is failing (the only package added was web-ext which has MPL 2.0) - I don't have access to Expensify's Snyk org.

**Review by tgolen — DISMISSED** [review]

**Review by dangrous — APPROVED** [review]

**Review by dangrous — APPROVED** [review]

**Review by tgolen — APPROVED** [review]

**Review by tgolen — DISMISSED** [review]
Trying to approve again.

**Comment by tgolen** [comment]
Still getting auto-rejected :(

**Review by dangrous — DISMISSED** [review]

**Comment by dangrous** [comment]
dang, thought i'd be lucky haha

**Comment by mjasikowski** [comment]
Waiting for GitHub to get back to me on the support ticket

**Comment by mjasikowski** [comment]
Waiting for GitHub to get back to me on the support ticket

**Comment by mjasikowski** [comment]
@dangrous @tgolen it's fixed now, closing and reopening PRs works

**Review by dangrous — APPROVED** [review]

**Comment by dangrous** [comment]
wooo

**Review by tgolen — APPROVED** [review]

**Comment by tgolen** [comment]
Yay, that worked. I'm publishing it now and then you can send out an email to everyone announcing the new version once I give you the green light.

**Comment by tgolen** [comment]
OK, green light! I've uploaded it to 1Password. 

> Send an email to @all to let anyone know they can update by following the steps from [I use firefox, how do I install the Kernel Scheduler (KS) browser extension?](https://stackoverflowteams.com/c/expensify/questions/7053/7054#7054)

**Comment by tgolen** [comment]
Here is an example email I sent out a while ago:

image

**Comment by mjasikowski** [comment]
@tgolen I'll go through the remaining snyk PRs, bump the version number and then deal with the e-mail - at least we'll have a "security updates" changelog entry for that

**Pull request merged**
