### PR TITLE
Derive initial checkbox state from query string

### PR DESCRIPTION
**Pull request by cead22**
## Tested various initial states

one | two
---|---
image|image
image|image

## And tested toggling the checkboxes
image

### CODE REVIEW

**Review by tgolen — COMMENTED** [review]
I guess this is fine, but I feel like if I allow it, I'm just gonna write another PR that does this using Onyx properly. The query params are not ideal because they are not discoverable. The only way people will use them is if they are specifically told and educated about them, and I think that's doing a disservice to the feature.

Also, in order to get a PR merged and deployed, you'll need to follow all the instructions in the readme. There are several version files you need to bump, for example.

**Comment by cead22** [comment]
> I guess this is fine, but I feel like if I allow it, I'm just gonna write another PR that does this using Onyx properly. 

Is that NAB?

>The query params are not ideal because they are not discoverable. The only way people will use them is if they are specifically told and educated about them, and I think that's doing a disservice to the feature.

I personally think that's fine for now. I don't know that anyone but me wants this right now

**Comment by tgolen** [comment]
OK, if that's what you would like, then sure :)

**Comment by cead22** [comment]
Haha yeah, I'd prefer shipping this quickly even if we decide to refactor it later, over having to learn how to re-implement this

**Comment by cead22** [comment]
Updated

**Review by tgolen — APPROVED** [review]

**Comment by tgolen** [comment]
I'll leave it to you to deploy this!

**Comment by cead22** [comment]
image

I submitted it for review on the chrome web store. Thanks for your help here. Do you think I should send an email to all@ to let everyone know about this feature?

**Pull request merged**
