### PR TITLE
Fix Label assignment

### PR DESCRIPTION
**Pull request by danieldoglas**
Labels are broken as per $https://github.com/Expensify/Expensify/issues/262805

GH now added spaces on before and after the property we use to determine the repo (`#repository-container-header strong a`). I've added a trim to remove that.

### How to test:

1. Run project locally following [readme.md](https://github.com/Expensify/k2-extension)
2. Try to assign a label in a test issue clicking on our k2 extension buttons (you can use this one https://github.com/Expensify/Expensify/issues/262808)

### Test evidence:

https://user-images.githubusercontent.com/5818999/219220283-e8af1a7c-33b7-46b4-86ba-736998348281.mov

### CODE REVIEW

**Review by rafecolton — COMMENTED** [review]
Will you please provide a little more information about how you tested this, why your change fixes the issue, and maybe some screenshots of it working locally?

**Review by luacmartins — COMMENTED** [review]
+1 to Rafe's comment. Also tests are failing.

**Comment by danieldoglas** [comment]
lol this error is not related to my changes. trying to figure it out

```
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

**Comment by danieldoglas** [comment]
Fixed

**Review by rafecolton — CHANGES_REQUESTED** [review]
Please also update the version in `assets/manifest.json` and `package-lock.json`

**Review by rafecolton — APPROVED** [review]

**Review by luacmartins — APPROVED** [review]

**Comment by danieldoglas** [comment]
deployed, awaiting review in both Firefox and Chrome.

**Pull request merged**
